node-id: LEGAL
port: 4002
monitoring-port: 9002
hydra-signing-key: keys/legal.sk
hydra-verification-key: keys/legal.vk
peers:
  - host: hydra-node-hr
    port: 4001
  - host: hydra-node-audit
    port: 4003
